version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: mysql-container    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    
volumes:
  mysql-volume:

